import type { EncyclopediaBook } from "./types";

export const MOCK_ENCYCLOPEDIAS: EncyclopediaBook[] = [
  {
    id: "enc-001",
    title: "موسوعة الفقه الإسلامي",
    author: "د. وهبة الزحيلي",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 1200,
    volumeCount: 12,
    category: "فقه",
    isNewRelease: true,
  },
  {
    id: "enc-002",
    title: "موسوعة القانون المدني",
    author: "أ.د. السنهوري",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 850,
    volumeCount: 8,
    category: "قانون مدني",
    isNewRelease: false,
  },
  {
    id: "enc-003",
    title: "الموسوعة الجنائية الكبرى",
    author: "د. محمود نجيب حسني",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 650,
    volumeCount: 6,
    category: "قانون جنائي",
    isNewRelease: true,
  },
  {
    id: "enc-004",
    title: "موسوعة أحكام النقض المدني",
    author: "د. أحمد أبو الوفا",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 980,
    volumeCount: 10,
    category: "أحكام قضائية",
    isNewRelease: false,
  },
  {
    id: "enc-005",
    title: "موسوعة القانون التجاري",
    author: "د. علي البارودي",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 720,
    volumeCount: 7,
    category: "قانون تجاري",
    isNewRelease: true,
  },
  {
    id: "enc-006",
    title: "موسوعة الإجراءات المدنية",
    author: "د. فتحي والي",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 540,
    volumeCount: 5,
    category: "إجراءات",
    isNewRelease: false,
  },
];
