import type { EncyclopediaBook } from "./types";

export const MOCK_ENCYCLOPEDIAS: EncyclopediaBook[] = [
  {
    id: "enc-001",
    title: "موسوعة الفقه الإسلامي",
    author: "د. وهبة الزحيلي",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 1200,
    volumeCount: 12,
    category: "فقه",
    isNewRelease: true,
  },
  {
    id: "enc-002",
    title: "موسوعة القانون المدني",
    author: "أ.د. السنهوري",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 850,
    volumeCount: 8,
    category: "قانون مدني",
    isNewRelease: false,
  },
  {
    id: "enc-003",
    title: "الموسوعة الجنائية الكبرى",
    author: "د. محمود نجيب حسني",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 650,
    volumeCount: 6,
    category: "قانون جنائي",
    isNewRelease: true,
  },
  {
    id: "enc-004",
    title: "موسوعة أحكام النقض المدني",
    author: "د. أحمد أبو الوفا",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 980,
    volumeCount: 10,
    category: "أحكام قضائية",
    isNewRelease: false,
  },
  {
    id: "enc-005",
    title: "موسوعة القانون التجاري",
    author: "د. علي البارودي",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 720,
    volumeCount: 7,
    category: "قانون تجاري",
    isNewRelease: true,
  },
  {
    id: "enc-006",
    title: "موسوعة الإجراءات المدنية",
    author: "د. فتحي والي",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 540,
    volumeCount: 5,
    category: "إجراءات",
    isNewRelease: false,
  },
  {
    id: "enc-007",
    title: "موسوعة المرافعات الشرعية",
    author: "أ. عبد الله بن محمد",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 600,
    volumeCount: 4,
    category: "مرافعات",
    isNewRelease: true,
  },
  {
    id: "enc-008",
    title: "موسوعة القانون الدولي العام",
    author: "د. صلاح الدين عامر",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 1100,
    volumeCount: 9,
    category: "قانون دولي",
    isNewRelease: false,
  },
  {
    id: "enc-009",
    title: "موسوعة العقود القانونية",
    author: "أ. محمد عبد الظاهر",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 780,
    volumeCount: 5,
    category: "عقود",
    isNewRelease: true,
  },
  {
    id: "enc-010",
    title: "موسوعة المسؤولية المدنية",
    author: "د. حسن علي الذنون",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 890,
    volumeCount: 8,
    category: "قانون مدني",
    isNewRelease: false,
  },
  {
    id: "enc-011",
    title: "موسوعة القضاء الإداري",
    author: "د. سليمان الطماوي",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 1350,
    volumeCount: 11,
    category: "قانون إداري",
    isNewRelease: true,
  },
  {
    id: "enc-012",
    title: "موسوعة التشريعات الجمركية",
    author: "أ. جلال أنور",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 480,
    volumeCount: 3,
    category: "تشريعات",
    isNewRelease: false,
  },
  {
    id: "enc-013",
    title: "موسوعة التحكيم التجاري",
    author: "د. أبو زيد رضوان",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 950,
    volumeCount: 6,
    category: "تحكيم",
    isNewRelease: true,
  },
  {
    id: "enc-014",
    title: "موسوعة الملكية الفكرية",
    author: "أ.د. سميحة القليوبي",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 820,
    volumeCount: 5,
    category: "ملكية فكرية",
    isNewRelease: false,
  },
  {
    id: "enc-015",
    title: "موسوعة قانون العمل السعودي",
    author: "د. أحمد بن خالد",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 700,
    volumeCount: 4,
    category: "قانون عمل",
    isNewRelease: true,
  },
  {
    id: "enc-016",
    title: "موسوعة جرائم المعلوماتية",
    author: "د. فهد بن عبد العزيز",
    coverUrl: "/assets/book-1.svg",
    priceEgp: 620,
    volumeCount: 3,
    category: "جرائم إلكترونية",
    isNewRelease: false,
  },
];
